kind: ReplicationController
apiVersion: v1
metadata:
  name: demo-server
  labels:
    name: demo-server
spec:
  replicas: 1
  selector:
    name: demo-server
  template:
    metadata:
      labels:
        name: demo-server
    spec:
      containers:
      - name: demo-server
        image: mickburgs/demo-server-service
        ports:
        - containerPort: 8080
